apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluestarth
  namespace: argocd
  labels:
    capsule.clastix.io/managed-by: prod
    projectcapsule.dev/tenant: prod
spec:
  project: bluestarth
  source:
    repoURL: https://github.com/infra-reel/blustarth.reeldev.jp.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bluestarth
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        capsule.clastix.io/tenant: prod
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
