apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluestarth
  namespace: mgmt-system+
spec:
  project: bluestarth
  source:
    repoURL: https://github.com/infra-reel/blustarth.reeldev.jp.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bluestarth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
